=== api-evangelist/star-wars/json-schema/film.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/api-evangelist/star-wars/main/json-schema/film.json",
  "title": "Film",
  "description": "A Star Wars film",
  "type": "object",
  "required": [
    "title",
    "episode_id",
    "opening_crawl",
    "director",
    "producer",
    "release_date",
    "characters",
    "planets",
    "starships",
    "vehicles",
    "species",
    "created",
    "edited",
    "url"
  ],
  "properties": {
    "title": {
      "type": "string",
      "description": "The title of this film"
    },
    "episode_id": {
      "type": "integer",
      "description": "The episode number of this film"
    },
    "opening_crawl": {
      "type": "string",
      "description": "The opening paragraphs at the beginning of this film"
    },
    "director": {
      "type": "string",
      "description": "The name of the director of this film"
    },
    "producer": {
      "type": "string",
      "description": "The name(s) of the producer(s) of this film"
    },
    "release_date": {
      "type": "string",
      "format": "date",
      "description": "The ISO 8601 date format of film release at original creator country"
    },
    "characters": {
      "type": "array",
      "description": "URLs of People resources featured in this film",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "planets": {
      "type": "array",
      "description": "URLs of Planet resources featured in this film",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "starships": {
      "type": "array",
      "description": "URLs of Starship resources featured in this film",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "vehicles": {
      "type": "array",
      "description": "URLs of Vehicle resources featured in this film",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "species": {
      "type": "array",
      "description": "URLs of Species resources featured in this film",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "created": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 date-time when this resource was created"
    },
    "edited": {
      "type": "string",
      "format": "date-time",
      "description": "ISO 8601 date-time when this resource was last edited"
    },
    "url": {
      "type": "string",
      "format": "uri",
      "description": "The hypermedia URL of this resource"
    }
  }
}

=== api-evangelist/star-wars/examples/film.json
{
  "title": "A New Hope",
  "episode_id": 4,
  "opening_crawl": "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
  "director": "George Lucas",
  "producer": "Gary Kurtz, Rick McCallum",
  "release_date": "1977-05-25",
  "characters": [
    "https://swapi.info/api/people/1",
    "https://swapi.info/api/people/2",
    "https://swapi.info/api/people/3",
    "https://swapi.info/api/people/4",
    "https://swapi.info/api/people/5"
  ],
  "planets": [
    "https://swapi.info/api/planets/1",
    "https://swapi.info/api/planets/2",
    "https://swapi.info/api/planets/3"
  ],
  "starships": [
    "https://swapi.info/api/starships/2",
    "https://swapi.info/api/starships/3",
    "https://swapi.info/api/starships/5"
  ],
  "vehicles": [
    "https://swapi.info/api/vehicles/4",
    "https://swapi.info/api/vehicles/6"
  ],
  "species": [
    "https://swapi.info/api/species/1",
    "https://swapi.info/api/species/2",
    "https://swapi.info/api/species/3"
  ],
  "created": "2014-12-10T14:23:31.880000Z",
  "edited": "2014-12-20T19:49:45.256000Z",
  "url": "https://swapi.info/api/films/1"
}
